services:
  database:
    container_name: database
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_filmes
    ports:
      - '5432:5432'
    volumes:
      - api_filmes_data:/var/lib/postgresql/data

volumes:
  api_filmes_data:
